### ISSUE TITLE
Create AdditionalFields

### ISSUE THREAD

**Issue by fuzzyfox** [fuzzyfox/flying-unicorn#7]
Create the additional fields model so that it works as intended, and allows for the addition of any field to any entity.

### Validation
Field validators should use the [Laravel Validation Rules](https://laravel.com/docs/5.6/validation#available-validation-rules) and be injected into the rules in the Store + Update requests.

### Permissions
The ability to get / set any of these additional fields is based on the entity it is attached to, and the slug stored on the field definition is appended to the permissions for the entity.

For example, if we add a `tito_id` field to `users`, and ommit the slug, then the ability to set / get the field is based on the permissions:

* `[own.]users.index`
* `[own.]users.store`
* `[own.]users.show`
* `[own.]users.update`
* `[own.]users.destroy`

However if the slug is stored (e.g. `tito`) the permissions for getting / setting become:

* `[own.]users.index.tito`
* `[own.]users.store.tito`
* `[own.]users.show.tito`
* `[own.]users.update.tito`
* `[own.]users.destroy.tito`

### ERD
Below is a simplified version of the table(s) and their relations. There are additional fields on each table used for tracking who added/updated the field defintions + when.
```
 +----------------+            +---------------------+          +-------------------+
 |AdditionalField |            |AdditionalFieldValue |          |Entity (e.g. User) |
 +----------------+            +---------------------+          +-------------------+
 |id              |<-----------+additional_field_id  |    +---->|id                 |
 |key             |            |entity_id            +----+     |name               |
 |type            |            |value                |          |email              |
 |entity          |            |                     |          |password           |
 +>alidator       |            +---------------------+          |                   |
 |permission_slug |                                             +-------------------+
 |                |
 +----------------+
```

### ToDo
* [x] Setup model
* [x] Create trait for adding to other models
* [ ] Create controller
    * [x] index
    * [ ] store
    * [x] show
    * [ ] update
    * [x] destroy
* [ ] Validate additional fields on store/update requests
* [ ] Create/Update additional fields on store/update requests
